# Generated by Django 2.0 on 2018-11-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.IntegerField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('itemNum', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('itemNum', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=30, unique=True)),
                ('itemDesc', models.TextField(default='description')),
                ('itemUnitPrice', models.FloatField(default=0)),
                ('itemImageName', models.CharField(max_length=50)),
                ('isEnabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('orderNum', models.AutoField(primary_key=True, serialize=False)),
                ('totalAmount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TableNum',
            fields=[
                ('tableNum', models.AutoField(primary_key=True, serialize=False)),
                ('tableKey', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderlist',
            name='tableNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.TableNum'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='orderList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.OrderList'),
        ),
    ]
