# Generated by Django 2.0 on 2018-11-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablenum',
            name='tableKey',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
