# Generated by Django 2.0 on 2018-11-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_backup_itemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
