# Generated by Django 2.0 on 2018-11-08 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_backup_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='timeOrderPlaced',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 11, 27, 30, 253558)),
        ),
    ]
