# Generated by Django 2.0 on 2018-11-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_orderlist_timeorderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='timeOrderPlaced',
            field=models.DateTimeField(null=True),
        ),
    ]
