# Generated by Django 2.0 on 2018-11-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='isVeg',
            field=models.BooleanField(default=True),
        ),
    ]
