# Generated by Django 2.0 on 2018-12-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20181223_0238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='orderList',
        ),
        migrations.RemoveField(
            model_name='tokenitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='tokenitem',
            name='tokens',
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='TokenItem',
        ),
    ]
