# Generated by Django 2.0 on 2018-12-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20181223_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.IntegerField()),
                ('timeStamp', models.DateTimeField()),
                ('itemNum', models.IntegerField()),
                ('itemName', models.CharField(default='NA', max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('tokenNum', models.IntegerField(unique=True)),
                ('orderNum', models.AutoField(primary_key=True, serialize=False)),
                ('totalAmount', models.FloatField(default=0)),
                ('timeOrderPlaced', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('tokenNum', models.AutoField(primary_key=True, serialize=False)),
                ('totalAmount', models.FloatField(default=0)),
                ('timetokenPlaced', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Menu')),
                ('tokens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Token')),
            ],
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='orderList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.OrderList'),
        ),
    ]
