# Generated by Django 2.0 on 2018-12-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20181223_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightBuffer',
            fields=[
                ('token', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('weight', models.FloatField(default=0.0)),
                ('hasValidData', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tokenitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
