# Generated by Django 2.0 on 2018-12-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20181225_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenitem',
            name='price',
        ),
    ]
