# Generated by Django 2.0 on 2019-01-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_tokenitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='price',
            field=models.FloatField(),
        ),
    ]
