# Generated by Django 2.0 on 2019-01-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20190104_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
